### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by bxlkm** [tiagocoutinho/multivisor#25] opened 2019-03-31 12:43 UTC
error: can't copy 'multivisor/server/dist/static': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-F25sdy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6TVN50/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-F25sdy/

/////////////////////////////////////////////////////////////////////////
/root/multivisor/multivisor/server/dist directory exists.

**Comment by tiagocoutinho** [comment] 2019-03-31 13:05
Hi @bxlkm,
Thanks for the report.

Could you describe in more detail the steps to reproduce the problem?

Specifically:
* which version of multivisor
* did you get the source from github or pypi
* python version
* are you using a virtual environment? or are you installing directly in the system as root?

**Comment by bxlkm** [comment] 2019-03-31 14:16
fix setup.py.
 package_data={'multivisor.multivisor.server': ['dist/*',
                                        'dist/static/css/*',
                                        'dist/static/js/*']},
Modify the directory multivisor.server to multivisor.multivisor.server through installation。

**Comment by dtackinc** [comment] 2019-04-11 13:18
hi, Multivisor looks very nice! I'm looking forward to trying it out.

I am getting the same error as the OP on install.
I'm cloned multivisor from github today (April 11, 2019).  
Python version is 2.7  
Not using a virtual environment. 
I'm using a docker image (see Dockerfile attached).  

Any help, hints or tips appreciated!


If I make the change mentioned by bxlkm for multivisor.multivisor.server (see the line with sed in the Dockerfile), then the installation continues and the supervisors and multivisor run, 

However, I get a 404 on port 22000 for any url I try, here is the example output:

ce7-multivisor    | 172.22.0.1 - - [2019-04-11 13:10:11] "GET / HTTP/1.1" 404 341 0.010764

**trying to get /api it's more verbose:**
ce7-multivisor    | ERROR 2019-04-11 13:10:16,715 flask.app: Exception on /api/ [GET]
ce7-multivisor    | Traceback (most recent call last):
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
ce7-multivisor    |     response = self.full_dispatch_request()
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
ce7-multivisor    |     rv = self.handle_user_exception(e)
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
ce7-multivisor    |     reraise(exc_type, exc_value, tb)
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
ce7-multivisor    |     rv = self.dispatch_request()
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
ce7-multivisor    |     return self.view_functions[rule.endpoint](**req.view_args)
ce7-multivisor    |   File "/usr/lib/python2.7/site-packages/multivisor/server/web.py", line 29, in catch_all
ce7-multivisor    |     return render_template("index.html")
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
ce7-multivisor    |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
ce7-multivisor    |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
ce7-multivisor    |     return self.get_template(template_name_or_list, parent, globals)
ce7-multivisor    |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
ce7-multivisor    |     return self._load_template(name, self.make_globals(globals))
ce7-multivisor    |   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
ce7-multivisor    |     template = self.loader.load(self, name, globals)
ce7-multivisor    |   File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
ce7-multivisor    |     source, filename, uptodate = self.get_source(environment, name)
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 58, in get_source
ce7-multivisor    |     return self._get_source_fast(environment, template)
ce7-multivisor    |   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
ce7-multivisor    |     raise TemplateNotFound(template)
ce7-multivisor    | TemplateNotFound: index.html


[Dockerfile.txt](https://github.com/tiagocoutinho/multivisor/files/3068776/Dockerfile.txt)

**Comment by guy881** [comment] 2019-04-14 18:54
Hi @dtackinc, I wasn't able to run your Dockerfile as it is using probably your private image "ce7". I tried running it with centos 7 image, but it didn't know the packages you intended to install. 
Instead, I changed your Dockerfile to use `python:2.7` image and pip install goes smoothly:

```Dockerfile
FROM python:2.7

RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs

RUN git clone https://github.com/guy881/multivisor.git

# Install frontend dependencies
RUN cd multivisor && npm install
# Build for production with minification
RUN cd multivisor && npm run build
RUN cd multivisor && pip install .
RUN mkdir multivisor/examples/full_example/log

# Finally, launch multivisor:
CMD cd multivisor && supervisord -c examples/full_example/supervisord_lid001.conf && multivisor -c examples/full_example/multivisor.conf
```
Although I can confirm that I was also unable to get anything else than 404. I've checked and this is happening because of my last changes to the routing. Sorry for that, I've already made a pull request to address this issue: https://github.com/tiagocoutinho/multivisor/pull/30

**Comment by dtackinc** [comment] 2019-04-15 13:26
hi @guy881 
Thanks for fixing the api routing and for sharing your dockerfile.  It worked fine and allowed us to continue our review and evaluation here at MaxIV in Lund. 
Best regards!
David

**Comment by tiagocoutinho** [comment] 2019-05-04 18:20
Ok, I am closing this issue since #30 seems to have fixed it.

**Closed by tiagocoutinho** 2019-05-04 18:20 UTC
